Bundle commons-io since gerrit core no longer provides it
By removing Solr from gerrit core in

  7fe1752bfdae0c280170ce2759146dc55bb6cd36

commons-io is no longer provided by the environment.
Building this plugin still worked, but loading it failed with:

  com.google.gerrit.server.plugins.PluginInstallException: org/apache/commons/io/FilenameUtils
  [...]
  Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils
  [...]
  fatal: Plugin failed to install. Cause: org/apache/commons/io/FilenameUtils

By moving commons-io to the explicit dependencies, the plugin loads
again with current gerrit core.

Change-Id: Ifb43baafc2d1ee190875802f3bc2a36fed5e7cef