Update patch set 1
Patch Set 1: Verified+1

Tested on Gerrit 2.15.3-5317-ge1f6585b1d

Current version of the plugin loads with:

  Sep 25 17:08:35 gerrithost docker[3472]: java.lang.NoClassDefFoundError: com/google/gerrit/common/TimeUtil
  Sep 25 17:08:35 gerrithost docker[3472]:         at com.googlesource.gerrit.plugins.rabbitmq.config.AMQProperties.getBasicProperties(AMQProperties.java:84)
  Sep 25 17:08:35 gerrithost docker[3472]:         at com.googlesource.gerrit.plugins.rabbitmq.session.type.AMQPSession.publish(AMQPSession.java:211)
  Sep 25 17:08:35 gerrithost docker[3472]:         at com.googlesource.gerrit.plugins.rabbitmq.message.MessagePublisher.publishEvent(MessagePublisher.java:177)
  Sep 25 17:08:35 gerrithost docker[3472]:         at com.googlesource.gerrit.plugins.rabbitmq.message.MessagePublisher.access$500(MessagePublisher.java:36)
  Sep 25 17:08:35 gerrithost docker[3472]:         at com.googlesource.gerrit.plugins.rabbitmq.message.MessagePublisher$2.run(MessagePublisher.java:97)
  Sep 25 17:08:35 gerrithost docker[3472]:         at java.lang.Thread.run(Thread.java:748)
  Sep 25 17:08:35 gerrithost docker[3472]: Caused by: java.lang.ClassNotFoundException: com.google.gerrit.common.TimeUtil
  Sep 25 17:08:35 gerrithost docker[3472]:         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  Sep 25 17:08:35 gerrithost docker[3472]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  Sep 25 17:08:35 gerrithost docker[3472]:         at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
  Sep 25 17:08:35 gerrithost docker[3472]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  Sep 25 17:08:35 gerrithost docker[3472]:         ... 6 more

With this patch the error is not present anymore.

Patch-set: 1
Reviewer: Gerrit User 1024846 <1024846@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=+1